### ISSUE TITLE
Is "type" parameter being used?

### ISSUE THREAD

**Issue by Saso222** [servocoder/RichFilemanager-PHP#7]
Hello,

According to the main RichFileManager repository's [wiki](https://github.com/servocoder/RichFilemanager/wiki/Passing-parameters-to-the-FM#restrict-the-view-to-images), you can pass the 'type' parameter to the initialisation of the plugin to restrict the view of certain files, for instance, to images.

I saw that the js plugin just send that parameter to the connector in order for it to list only the desired files (I guess). This is not working for me and I can't find anywhere in the PHP connector where this parameter is being used. Is it implemented yet?.

Moreover, wouldn't be the idea that this parameter also restrict which files can you upload?

Best,
Ignacio

**Comment by servocoder** [comment]
The `type` parameter is the legacy from original RichFilemanager
According to the new security model it's not secure to pass parameter to the server in order to set allowed files extensions list. Thus `type` parameter is ignored in the last versions.

However it might be a good idea to use `type` parameter for client-side filtering, just to hide non-image files in case the type `image` is set. It will not affect to files returned in the connector's response. You have to use server-side config for this.

Also, since you may want to define you own extensions list for `images` filter I think the JSON config file should be extended with `filter` option, where you can define you own associations. Example:

```json
{
  "filter": {
    "images": ["jpg", "gif", "png"],
    "media": ["mp3", "avi"],
    "custom": ["pdf", "md", "doc"]
  }
}
```

How do you like this idea?

**Comment by Saso222** [comment]
I really like the idea, specially the config.filter section.

Do you want me to implement this? I would do it as soon as I can.

**Comment by servocoder** [comment]
Sure, I will appreciate your help.
I have created a new issue in the main repo and assign it to you: https://github.com/servocoder/RichFilemanager/issues/204

Please take a look criterias I have outlined there.
